#pragma once

#include <cstdint>

namespace robot {

enum class Task : uint8_t {
  STOPPED = 0,

  //
  // 1-10: maze tasks.
  //

  MAZE_SEARCH = 1,
  MAZE_SLOW_SOLVE = 2,
  MAZE_FAST_SOLVE = 3,

  MAZE_SEARCH_START_STOP_MOTION = 4,
  MAZE_SEARCH_TWO_TIMES = 5,  // To goal, to outside start, to goal, to start.
  MAZE_SEARCH_TWO_TIMES_START_STOP_MOTION = 6,
  MAZE_SOLVE_WITH_SEARCH_NAVIGATION = 7,
  MAZE_SOLVE_WITH_SEARCH_NAVIGATION_START_STOP_MOTION = 8,
  MAZE_SEARCH_FASTER = 9,
  MAZE_SEARCH_THEN_SLOW_SOLVE_THEN_FAST_SOLVE = 10,

  //
  // 11-40: test drive tasks.
  //

  TEST_DRIVE_STRAIGHT_FROM_BACK_WALL_TO_SENSE_SPOT = 11,
  TEST_DRIVE_STRAIGHT_ONE_CELL = 12,
  TEST_DRIVE_TURN_RIGHT_FROM_SENSE_SPOT_TO_SENSE_SPOT = 13,
  TEST_DRIVE_TURN_LEFT_FROM_SENSE_SPOT_TO_SENSE_SPOT = 14,
  TEST_DRIVE_TURN_RIGHT_IN_PLACE = 15,
  TEST_DRIVE_TURN_LEFT_IN_PLACE = 16,
  TEST_DRIVE_TURN_180_IN_PLACE = 17,
  TEST_GYRO = 18,
  TEST_DRIVE_STRAIGHT_FOUR_CELLS_FROM_BACK_WALL_WITH_VISION_ALIGN = 19,
  TEST_DRIVE_RAW_SPEEDS = 20,
  TEST_DRIVE_CONSTANT_SPEED = 21,

  DRIVE_BACKUP_INTO_WALL = 22,

  //
  // 41-50: Other
  //

  MANUAL_CHASSIS_SPEEDS = 41,
  IDLE = 42,

  //
  // 128+: Internal
  //

  ARMED = 128,
  ARMED_TRIGGERING,
  ARMED_TRIGGERED,

  VISION_CALIBRATE,
};

const char* task_to_string(Task task);

}  // namespace robot
