#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

// Topics received from the dashboard.
enum {
  FB_TOPIC_RECEIVE_MAIN_TASK,
  FB_TOPIC_RECEIVE_MAIN_COMMAND,
  FB_TOPIC_RECEIVE_MAIN_SONG,

  FB_TOPIC_RECEIVE_DRIVE_PID,
  FB_TOPIC_RECEIVE_DRIVE_CHASSIS_SPEEDS,

  _FB_TOPIC_RECEIVE_COUNT,
};

// Topics published by the robot.
enum {
  FB_TOPIC_SEND_MAIN_TASK,
  FB_TOPIC_SEND_MAIN_ERROR,
  FB_TOPIC_SEND_MAIN_SONG,
  FB_TOPIC_SEND_MAIN_STATUS,

  FB_TOPIC_SEND_VISION_RAW_READINGS,
  FB_TOPIC_SEND_VISION_DISTANCES,

  FB_TOPIC_SEND_DRIVE_MOTOR_DATA,
  FB_TOPIC_SEND_DRIVE_IMU_DATA,
  FB_TOPIC_SEND_DRIVE_PID,
  FB_TOPIC_SEND_DRIVE_CHASSIS_SPEEDS,

  FB_TOPIC_SEND_MAZE_CELL,
  FB_TOPIC_SEND_MAZE_MOUSE_POSITION,

  _FB_TOPIC_SEND_COUNT,
};

#ifdef __cplusplus
}
#endif
