#pragma once

#include <micromouse/feedback_topic.h>
#include <cstdint>

// Topics received from the dashboard.
enum class FeedbackTopicReceive : uint8_t {
  MAIN_TASK = FB_TOPIC_RECEIVE_MAIN_TASK,

  DRIVE_PID = FB_TOPIC_RECEIVE_DRIVE_PID,
  DRIVE_CHASSIS_SPEEDS = FB_TOPIC_RECEIVE_DRIVE_CHASSIS_SPEEDS,

  VISION_CALIBRATE = FB_TOPIC_RECEIVE_VISION_CALIBRATE,

  MAZE_RESET = FB_TOPIC_RECEIVE_MAZE_RESET,

  MUSIC_PLAY_SONG = FB_TOPIC_RECEIVE_MUSIC_PLAY_SONG,
};

// Topics published by the robot.
enum class FeedbackTopicSend : uint8_t {
  MAIN_TASK = FB_TOPIC_SEND_MAIN_TASK,
  MAIN_ERROR = FB_TOPIC_SEND_MAIN_ERROR,

  DRIVE_MOTOR_DATA = FB_TOPIC_SEND_DRIVE_MOTOR_DATA,
  DRIVE_IMU_DATA = FB_TOPIC_SEND_DRIVE_IMU_DATA,
  DRIVE_PID = FB_TOPIC_SEND_DRIVE_PID,
  DRIVE_CHASSIS_SPEEDS = FB_TOPIC_SEND_DRIVE_CHASSIS_SPEEDS,

  VISION_RAW_READINGS = FB_TOPIC_SEND_VISION_RAW_READINGS,
  VISION_DISTANCES = FB_TOPIC_SEND_VISION_DISTANCES,
  VISION_CALIBRATE = FB_TOPIC_SEND_VISION_CALIBRATE,

  MAZE_CELL = FB_TOPIC_SEND_MAZE_CELL,
  MAZE_MOUSE_POSITION = FB_TOPIC_SEND_MAZE_MOUSE_POSITION,

  MUSIC_IS_PLAYING = FB_TOPIC_SEND_MUSIC_IS_PLAYING,
};
