#pragma once

#include <micromouse/feedback_topic.h>
#include <cstdint>

// Topics received from the dashboard.
enum class FeedbackTopicReceive : uint8_t {
  MAIN_TASK = FB_TOPIC_RECEIVE_MAIN_TASK,
  MAIN_COMMAND = FB_TOPIC_RECEIVE_MAIN_COMMAND,
  MAIN_SONG = FB_TOPIC_RECEIVE_MAIN_SONG,

  DRIVE_PID = FB_TOPIC_RECEIVE_DRIVE_PID,
  DRIVE_CHASSIS_SPEEDS = FB_TOPIC_RECEIVE_DRIVE_CHASSIS_SPEEDS,
};

// Topics published by the robot.
enum class FeedbackTopicSend : uint8_t {
  MAIN_TASK = FB_TOPIC_SEND_MAIN_TASK,
  MAIN_ERROR = FB_TOPIC_SEND_MAIN_ERROR,
  MAIN_SONG = FB_TOPIC_SEND_MAIN_SONG,
  MAIN_STATUS = FB_TOPIC_SEND_MAIN_STATUS,

  VISION_RAW_READINGS = FB_TOPIC_SEND_VISION_RAW_READINGS,
  VISION_DISTANCES = FB_TOPIC_SEND_VISION_DISTANCES,

  DRIVE_MOTOR_DATA = FB_TOPIC_SEND_DRIVE_MOTOR_DATA,
  DRIVE_IMU_DATA = FB_TOPIC_SEND_DRIVE_IMU_DATA,
  DRIVE_PID = FB_TOPIC_SEND_DRIVE_PID,
  DRIVE_CHASSIS_SPEEDS = FB_TOPIC_SEND_DRIVE_CHASSIS_SPEEDS,

  MAZE_CELL = FB_TOPIC_SEND_MAZE_CELL,
  MAZE_MOUSE_POSITION = FB_TOPIC_SEND_MAZE_MOUSE_POSITION,
};
