# ----------------------------
# Makefile Options
# ----------------------------

NAME = MOUSE
# ICON = icon.png
DESCRIPTION = "MicroMouse Controller"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -pedantic -Werror  -Oz
CXXFLAGS = -Wall -Wextra -pedantic -Werror  -Oz

# ----------------------------

include $(shell cedev-config --makefile)
